AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
    EnvironmentName:
      Type: String
    EnvironmentNumber:
      Type: String

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      # For options see https://docs.aws.amazon.com/lambda/latest/dg/API_TracingConfig.html
      Tracing: Active
      Runtime: go1.x
      CodeUri: ./handler.zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - AmazonSSMFullAccess
      Environment:   
        Variables:
          ENVIRONMENT_NAME:
            Ref: EnvironmentName
          ENVIRONMENT_NUMBER:
            Ref: EnvironmentNumber

Outputs:
  FunctionArn:
    Value: !GetAtt Function.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"